# -*- coding: utf-8 -*-
"""automatic_algorithm_comparision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWbtHFSP2isns-t4H9d5GlHPCFIeiNfH
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import kagglehub
path = kagglehub.dataset_download("vjchoudhary7/customer-segmentation-tutorial-in-python")

import os
os.listdir(path)

data = pd.read_csv(path + "/Mall_Customers.csv")

data

data.isnull().sum()

data.duplicated().sum()

X = data.drop(['Spending Score (1-100)'],axis=1)
Y = data['Spending Score (1-100)']

from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

X_train

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder # Changed LabelEncoder to OneHotEncoder
from sklearn.compose import ColumnTransformer

# Identify numerical and categorical columns
categorical_features = ['Gender']
numerical_features = ['CustomerID', 'Age', 'Annual Income (k$)']

# Create preprocessing pipelines for numerical and categorical features
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore')) # Using OneHotEncoder
])

# Create a preprocessor using ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

x_train_pre = preprocessor.fit_transform(X_train)

x_train_pre

from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
from sklearn.metrics import silhouette_score

def run_algorithms(X):

    results = {}

    # KMeans
    kmeans = KMeans(n_clusters=3, random_state=42)
    labels_k = kmeans.fit_predict(X)
    results["KMeans"] = silhouette_score(X, labels_k)

    # DBSCAN
    dbscan = DBSCAN(eps=0.5, min_samples=5)
    labels_d = dbscan.fit_predict(X)
    results["DBSCAN"] = silhouette_score(X, labels_d)

    # Hierarchical
    hc = AgglomerativeClustering(n_clusters=3)
    labels_h = hc.fit_predict(X)
    results["Hierarchical"] = silhouette_score(X, labels_h)

    best_algo = max(results, key=results.get)

    print("Scores:", results)
    print("Best Algorithm:", best_algo)

    return best_algo

run_algorithms(x_train_pre)

import pickle

pickle.dump(preprocessor,open('preprocessor.pkl','wb'))

